### ISSUE TITLE
dont know how to work it :( [Mac]

### ISSUE THREAD

**Issue by heythere-ux** [robinovitch61/webtoon-dl#16]
hi so i downloaded the binary and tried to enter the stuff into terminal (webtoon-dl "<your-webtoon-series-url>"), and it doesn't work.

yes I did replace the directions with the URL if you were wondering

**Comment by robinovitch61** [comment]
Please see the usage section of the readme https://github.com/robinovitch61/webtoon-dl?tab=readme-ov-file#usage

Running with an `""` empty string doesn't specify what to download, so it won't work
