### ISSUE TITLE
Mac OS Darwin terminal no usage issue

### ISSUE THREAD

**Issue by Averywaybright** [robinovitch61/webtoon-dl#7]
Read and checkbox the following by putting an "x" in the brackets like `- [x]` before submitting this bug report:

- [x] I have searched existing issues, opened and closed, for existing solutions to my problem
- [x] I understand that I have to fill out all of the following or risk my issue being closed and locked

**What you ran, all the output, and the entire error message, if any**
```
<I downloaded the latest Darwin file and opened the dl file, when I did it said all was successful opening it but I cannot paste or type anything thus not allowing me to use the downloader. Did I do something wrong?>
```

**Expected behavior**
i thought I would be able to use this command: webtoon-dl --eps-per-file=1000000 "<https://www.webtoons.com/en/canvas/its-them/list?title_no=386017&page=7>"

or this one in case I got it wrong : webtoon-dl --eps-per-file=1000000 "<https://www.webtoons.com/en/canvas/its-them/secret-trade/viewer?title_no=386017&episode_no=1>"
 in order to download the entire comic series onto a single file
**Screenshots**
.
<img width="561" alt="Screenshot 2024-03-28 at 11 29 04 AM" src="https://github.com/robinovitch61/webtoon-dl/assets/165318332/f8381250-32cf-4d53-99c6-58679810c8bf">

**Complete the following information:**
 - OS [e.g. Mac, Windows, Ubuntu, Arch, NixOS, etc.]: <your OS here>
 - Version [e.g. v0.0.5]: <the version here>
 - Available space on disk [e.g. 10GB]: <your value here>
 - RAM [e.g. 8GB]: <your value here>

**Additional context**

**Comment by robinovitch61** [comment]
Closing as this is an issue with invoking the correct command, not actually with the tool itself. Let me know if you run into any other trouble with using the tool, happy to help guide.
